Fix MSVC 14.42.34433 compiler crash
For unknown reasons, this compiler version crashes with error C1001:
Internal compiler error.

This patch was found by trial and error and works but I do not know
why it fixes things (on my computer at least).

If I were to guess (with the fixes in mind), it is due to some kind
of name-dependant lookup that it can not handles or find in some
compilation context.